# Generated by Django 2.0.3 on 2018-05-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_alerta', models.CharField(max_length=200)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('descripcion_alerta', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_bodega', models.CharField(max_length=100)),
                ('telefono_bodega', models.IntegerField()),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEstablecimientoVenta',
            fields=[
                ('id_establecimiento_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_establecimiento', models.IntegerField()),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_establecimiento_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido_empleado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_empleado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_productos', models.IntegerField()),
                ('precio_unitario_producto', models.IntegerField()),
                ('total_impuesto', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('nombre_establecimiento_venta', models.CharField(max_length=100)),
                ('fecha_venta', models.DateTimeField()),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePrecioProducto',
            fields=[
                ('id_detalle_precio_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_precio_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(max_length=10)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('direccion_empleado', models.CharField(max_length=100)),
                ('correo_empleado', models.CharField(max_length=100)),
                ('contrasenia_empleado', models.CharField(max_length=32)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'estado_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_unidad', models.IntegerField()),
                ('fecha_venta', models.DateTimeField()),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField()),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_medio_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medio_pago', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'medio_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_de_barras', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('detalle_producto', models.CharField(max_length=1000)),
                ('direccion_foto_producto', models.CharField(max_length=200)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('no_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('rut_surcursal', models.CharField(max_length=11)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('direccion_sucursal', models.CharField(max_length=100)),
                ('telefono_sucursal', models.IntegerField()),
                ('horario_de_atencion_sucursal', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('no_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('direccion_tienda', models.CharField(max_length=100)),
                ('contacto_tienda', models.CharField(max_length=100)),
                ('horario_atencion', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaOnline',
            fields=[
                ('id_tienda_online', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda_online', models.CharField(max_length=100)),
                ('direccion_tienda_online', models.CharField(max_length=100)),
                ('contacto_tienda_online', models.CharField(max_length=200)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tienda_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBodega',
            fields=[
                ('id_tipo_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_bodega', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id_tipo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_cargo', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPrecio',
            fields=[
                ('id_tipo_precio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_precio', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_precio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('correo_usuario', models.CharField(max_length=200)),
                ('contrasenia_usuario', models.CharField(max_length=32)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
